name: CI

on: 
  # push:
  #   branches: 
  #     - main
  # pull_request:
  #   branches: 
  #     - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: https://registry.npmjs.org

    - run: npm install -g yarn

    - name: Installing dependencies
      run: yarn install --frozen-lockfile

    - name: Compile
      run: yarn build

    - name: Run Tests
      run: yarn test
      env:
        AVALANCHE_DEPLOY_RPC: ${{ secrets.AVALANCHE_DEPLOY_RPC }}
        AVALANCHE_DEPLOY_RPC_TEST: ${{ secrets.AVALANCHE_DEPLOY_RPC_TEST }}
        AVALANCHE_FORK_RPC: ${{ secrets.AVALANCHE_FORK_RPC }}
        PK_DEPLOYER: ${{ secrets.PK_DEPLOYER }}
        SNOWTRACE_API_KEY: ${{ secrets.SNOWTRACE_API_KEY }}
